### PR TITLE
Docs initialization

### PR DESCRIPTION
**Pull request by AndrzejM63**
This change is [Reviewable](https://reviewable.io/reviews/socialwifi/flask-jsonapi/19)

### CODE REVIEW

**Comment by riklaunim** [comment]
*[docs/index.rst, line 4 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20eVONG30ZgRrDE1xM:-L20eVOObDiFBRBrOxOK:bbinro0) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/index.rst#L4)):*
> ```reStructuredText
>    sphinx-quickstart on Fri Dec 29 14:00:46 2017.
>    You can adapt this file completely to your liking, but it should at least
>    contain the root `toctree` directive.
> ```

czy to jest potrzebne?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 4 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20eoq5cQtLdZQ1wv80:-L20eoq5cQtLdZQ1wv81:b4mt2n3) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L4)):*
> ```reStructuredText
> ++++++++++++
> 
> The lightweight applications (those one based on Flask) needs to use JSON too.
> ```

trochę dziwne to zdanie i nie wyjaśnia co to jest za pakiet.  Bardziej coś w rodzaju:

flask-jsonapi is a server implementation of JSON API for Flask. It allows for rapid creation of API endpoints using this format. Such endpoints can be then used by other services or single page applications based on Ember.js, React, Angular.js and alike.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 19 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20fqWyqEdSpgsuRHSD:-L20fqWzT09EH4GQxCXh:baj6jk) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L19)):*
> ```reStructuredText
> ++++++++++++
> 
> This package requires at least python 3.5.
> ```

powtórzenie. Raczej zbędne.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 27 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20g6nB3_LVex4EJ4Tz:-L20g6nB3_LVex4EJ4U-:b-2qksl8) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L27)):*
> ```reStructuredText
> ++++++++++++++++++
> 
> Run in python::
> ```

długi blok kodu bardziej pasuje do pliku niż copy-paste do shella.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 38 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20gN4Sz5OZX3if4iLt:-L20gN4Sz5OZX3if4iLu:b7eew71) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L38)):*
> ```reStructuredText
> 
>     class ExampleSchema(marshmallow_jsonapi.Schema):
>         id = marshmallow_jsonapi.fields.UUID()
> ```

my używamy uuidów, ale nie każdy może załapać skąd te dziwne id się biorą niżej. najprostszy przykład raczej powinien operować na liczbach jako id.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 47 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20gay3w9vlBnAlfRtb:-L20gay3w9vlBnAlfRtc:b-l6a81) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L47)):*
> ```reStructuredText
>     ExampleModel = collections.namedtuple('ExampleModel', 'id body')
> 
>     repository = {
> ```

to wygląda dość magicznie i może być trudne do zrozumienia.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 64 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20guyTDgP-3RdGlQG2:-L20guyTDgP-3RdGlQG3:b41eyjm) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L64)):*
> ```reStructuredText
>             return list(repository.values())
> 
>         def create(self, data):
> ```

własne implementacje tych metod są potrzebne? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 153 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20h6xPS-KihInTeZDL:-L20h6xPS-KihInTeZDM:bg8ioi) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L153)):*
> ```reStructuredText
> To run tests::
> 
>     virtualenv -p python3.6 ~/flask-jsonapi-virtualenv
> ```

-p python3 a nie -p python3.6

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 168 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20hOtEYCoZu_maA5ar:-L20hOtEYCoZu_maA5as:bp2bx44) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L168)):*
> with the some data source
? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 169 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20hb-gqm7JEMRTjK8m:-L20hb-gqm7JEMRTjK8n:b-8a2uej) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L169)):*
> Which is somehow

which występuje po przecinku a nie jako początek nowego zdania. "Somehow" bym wyrzucił.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 181 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20iGiALGjfw6EpojdV:-L20iGiALGjfw6EpojdW:b-cyfo83) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L181)):*
> , sorry flask-jsonapi will start soon.
do wyrzucenia.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 186 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20iLIWp7BMb0uZ9BK4:-L20iLIWp7BMb0uZ9BK5:b-2pua9n) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L186)):*
> Below example
example below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 273 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20iVzdY5Mq8Gw25Ajn:-L20iVzdY5Mq8Gw25Ajo:b-ygfjq4) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L273)):*
> ```reStructuredText
>         api.repository(endpoints.PostRepositoryViewSet(), 'post', '/posts/')
>         api.repository(endpoints.UserRepositoryViewSet(), 'user', '/users/')
> ```

ogólnie angielski do poprawy. Ciężko się to czyta.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by riklaunim** [comment]
*[docs/introduction.rst, line 162 at r1](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19#-L20ilSpW7JMcnOlr-sb:-L20ilSpW7JMcnOlr-sc:b-iy0408) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/88a06314f06ae9edcf52688928d7aa3b41e781ca/docs/introduction.rst#L162)):*
> Just to make your life easier

smalltalk raczej zbędny ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/19)*

**Comment by jgoclawski** [comment]
I've made a "docs" branch with this commit.
You can preview how it looks at RTD here: https://flask-jsonapi.readthedocs.io/en/docs/

Let me know, when you push some updates and want the docs to be regenerated.

**Review by jgoclawski — APPROVED** [review]

**Pull request merged**
