### PR TITLE
Add atomic_schema as repository_field.

### PR DESCRIPTION
**Pull request by mimo00**
This change is [Reviewable](https://reviewable.io/reviews/socialwifi/flask-jsonapi/10)

### CODE REVIEW

**Comment by mimo00** [comment]
@jgoclawski review please.

**Comment by riklaunim** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/10#-:-Ky1BKqQEHg_8FFME2KH:bnfp4nl)*

**Comment by jgoclawski** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/10#-:-Kya1YZ0ZgxR-2f_pYJk:bnfp4nl)*

**Comment by jgoclawski** [comment]
Reviewed 3 of 4 files at r4, 10 of 10 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[flask_jsonapi/nested/nested_resource_repositories.py, line 1 at r5](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/10#-KyaKo0qUcHvGTxfpbzk:-KyaKo0qUcHvGTxfpbzl:b3bdciv) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/378fbea6d8a824a70c811b4d49c894cc549e9bd9/flask_jsonapi/nested/nested_resource_repositories.py#L1)):*
> ```Python
> import flask_jsonapi.nested.nested_resources
> ```

inconsistent imports:

  from flask_jsonapi.nested import nested_resourcesnxn

---

*[flask_jsonapi/nested_resource_repositories.py, line 8 at r4](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/10#-KyaJtCX7YcC0YEd0A_a:-KyaJtCX7YcC0YEd0A_b:bkiz0cj) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/3d0c9248fea6664a07e4d5801902e873b1d4a13c/flask_jsonapi/nested_resource_repositories.py#L8)):*
> NotImplementedProperty('schema')

'nested_schema' as argument

---

*[flask_jsonapi/nested_resource_repositories.py, line 10 at r4](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/10#-KyaLNTwwTMrCaaA5tw7:-KyaLNTwwTMrCaaA5tw8:b-m5d5od) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/3d0c9248fea6664a07e4d5801902e873b1d4a13c/flask_jsonapi/nested_resource_repositories.py#L10)):*
> nested_schema

this should be a required argument, no? if yes, then the "if" below is not required.

---

*[flask_jsonapi/nested_resource_repositories.py, line 24 at r4](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/10#-KyaKOgD4dGo3ZaXq8O-:-KyaKOgD4dGo3ZaXq8O0:b84ydty) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/3d0c9248fea6664a07e4d5801902e873b1d4a13c/flask_jsonapi/nested_resource_repositories.py#L24)):*
> get_nested_schema_kwargs

how about "get_list_view_kwargs" ?

---

*[flask_jsonapi/nested_resource_repositories.py, line 25 at r4](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/10#-KyaKJ5K2erZMuZ9Y7e-:-KyaKJ5K2erZMuZ9Y7e0:boihb9d) ([raw file](https://github.com/socialwifi/flask-jsonapi/blob/3d0c9248fea6664a07e4d5801902e873b1d4a13c/flask_jsonapi/nested_resource_repositories.py#L25)):*
> super()

self

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/10)*

**Comment by jgoclawski** [comment]
:lgtm:

---

Reviewed 2 of 10 files at r5, 8 of 10 files at r6, 9 of 9 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/flask-jsonapi/10#-:-KyqGOOuubgSLT1dziai:bnfp4nl)*

**Pull request merged**
